"""Make student_id unique in attendance table

Revision ID: b6db1963b002
Revises: cbb3158c2d66
Create Date: 2026-02-11 14:06:14.072936

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b6db1963b002'
down_revision = 'cbb3158c2d66'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_attendance_student_id'), 'attendance', ['student_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_attendance_student_id'), table_name='attendance')
    # ### end Alembic commands ###
