"""Move login_count from students to attendance table

Revision ID: cbb3158c2d66
Revises: 5454078a24dd
Create Date: 2026-02-11 13:50:01.512923

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'cbb3158c2d66'
down_revision = '5454078a24dd'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('attendance', sa.Column('login_count', sa.Integer(), nullable=True))
    op.drop_column('students', 'login_count')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students', sa.Column('login_count', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('attendance', 'login_count')
    # ### end Alembic commands ###
