"""Add last_login_date column to attendance table

Revision ID: e0da99c7e41a
Revises: b6db1963b002
Create Date: 2026-02-13 15:59:48.544170

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e0da99c7e41a'
down_revision = 'b6db1963b002'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('attendance', sa.Column('last_login_date', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('attendance', 'last_login_date')
    # ### end Alembic commands ###
